---
- name: Unarchive a file that is already on the local path
  ansible.builtin.unarchive:
    src: files/artifact.tar.gz
    dest: ~/
 
- name: start app
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start ~/dist/main.js -f