Description: >
  Cloudfront distribution for UdaPeople.

Parameters:
  WorkflowID2:
    Description: Unique identifier.
    Type: String


Resources:
  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${WorkflowID2}.s3.amazonaws.com"
            Id: webpage
            CustomOriginConfig:
              - HTTPPort: 80
                OriginProtocolPolicy: http-only
        Enabled: True
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all

Outputs:
  WorkflowID2:
    Value: !Sub ${WorkflowID2}
    Description: URL for website hosted on S3
    Export:
      Name: WorkflowID2
